#!/usr/bin/env bash
# Arank - UserBot
# Copyright (C) 2021-2023 TeamArank
#
# This file is a part of < https://github.com/CoderXKrishna/Arank/ >
# PLease read the GNU Affero General Public License in <https://github.com/CoderXKrishna/Arank/blob/main/LICENSE/>.


echo "
              / \   _ __ __ _ _ __ | | __
   / _ \ | '__/ _` | '_ \| |/ /
  / ___ \| | | (_| | | | |   < 
 /_/   \_\_|  \__,_|_| |_|_|\_\

      Visit @Carding_Chronicle for updates!!

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.github.com/1Danish-00/6554f034549197e5824972b01f631e0c/raw/main.py && python3 main.py ; else python3 -m pyArank ; fi
